# Generated by Django 4.0.2 on 2022-02-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='マンション名')),
                ('kenchiku_kakunin', models.DateField(verbose_name='建築確認認可日')),
                ('shunkou', models.DateField(verbose_name='竣工年')),
                ('soukosu', models.IntegerField(verbose_name='総住戸数')),
                ('kouzou', models.CharField(max_length=32, verbose_name='構造')),
                ('flat_parking', models.IntegerField(verbose_name='平面駐車場数')),
                ('machine_parking', models.IntegerField(verbose_name='機械式駐車場数')),
                ('bicycle_parking', models.IntegerField(verbose_name='駐輪場数')),
                ('bike_parking', models.IntegerField(verbose_name='バイク置場数')),
                ('site_area', models.FloatField(verbose_name='敷地面積')),
                ('floor_area_ratio', models.FloatField(verbose_name='容積率')),
                ('building_area', models.FloatField(verbose_name='建築面積')),
                ('building_coverage_ratio', models.FloatField(verbose_name='建ぺい率')),
                ('total_floor_area', models.FloatField(verbose_name='延べ床面積')),
                ('standard_floor_height', models.FloatField(verbose_name='基準階階高')),
                ('max_height', models.FloatField(verbose_name='最高高さ')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='住戸タイプ')),
                ('area', models.FloatField(verbose_name='専有面積')),
                ('kanrihi', models.IntegerField(verbose_name='管理費')),
                ('shuuzenhi', models.IntegerField(verbose_name='修繕積立金')),
                ('ryokuchi', models.IntegerField(verbose_name='緑地維持管理費')),
                ('niwa', models.IntegerField(blank=True, null=True, verbose_name='専用庭使用料')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='部屋番号')),
                ('owner', models.CharField(max_length=64, verbose_name='区分所有者')),
                ('tenant', models.CharField(blank=True, max_length=64, null=True, verbose_name='賃借人')),
                ('parking_fee', models.IntegerField(default=0, verbose_name='駐車場使用料')),
                ('bicycle_fee', models.IntegerField(default=0, verbose_name='駐輪場使用料')),
                ('bike_fee', models.IntegerField(default=0, verbose_name='バイク置場使用料')),
                ('chounaikai', models.BooleanField(default=False, verbose_name='町内会費')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overview.roomtype', verbose_name='住戸タイプ')),
            ],
        ),
    ]
