# Generated by Django 4.0.2 on 2022-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_alter_overview_shunkou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='standard_floor_height',
            field=models.CharField(max_length=32, verbose_name='基準階階高'),
        ),
    ]
