# Generated by Django 4.0.2 on 2022-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_alter_overview_standard_floor_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='bouka_cjhiiki',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='防火地域'),
        ),
        migrations.AddField(
            model_name='overview',
            name='constraction',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='施工会社'),
        ),
        migrations.AddField(
            model_name='overview',
            name='height_limit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='高度制限'),
        ),
        migrations.AddField(
            model_name='overview',
            name='management',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='管理会社'),
        ),
        migrations.AddField(
            model_name='overview',
            name='private_water_equipment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='専有部給水設備'),
        ),
        migrations.AddField(
            model_name='overview',
            name='public_water_equipment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='共用部給水設備'),
        ),
        migrations.AddField(
            model_name='overview',
            name='required_parking',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='必要駐車場台数'),
        ),
        migrations.AddField(
            model_name='overview',
            name='seller',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='分譲会社'),
        ),
        migrations.AddField(
            model_name='overview',
            name='specified_building_coverage_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='指定建ぺい率'),
        ),
        migrations.AddField(
            model_name='overview',
            name='specified_floor_area_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='指定容積率'),
        ),
        migrations.AddField(
            model_name='overview',
            name='trunk_room',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='トランクルーム'),
        ),
        migrations.AddField(
            model_name='overview',
            name='youto_chiiki',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用途地域'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(max_length=16, verbose_name='住戸タイプ'),
        ),
    ]
