# Generated by Django 4.0.3 on 2022-05-03 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_alter_room_building_alter_room_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日'),
        ),
    ]
