# Generated by Django 4.0.2 on 2022-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_overview_bouka_cjhiiki_overview_constraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='delivery_box',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='宅配ボックス'),
        ),
    ]
