# Generated by Django 4.0.4 on 2022-05-23 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_room_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='parking_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='駐車場使用料更新日'),
        ),
    ]
