# Generated by Django 4.0.2 on 2022-02-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_overview_delivery_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overview',
            old_name='bouka_cjhiiki',
            new_name='bouka_chiiki',
        ),
    ]
