# Generated by Django 4.0.4 on 2022-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_room_parking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='parking_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='駐車場使用料更新日'),
        ),
    ]
