# Generated by Django 5.0.6 on 2024-05-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_overview_entrance_overview_security'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
