# Generated by Django 4.0.2 on 2022-02-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_alter_roomtype_niwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='number_unit',
            field=models.IntegerField(default=0, verbose_name='住戸数'),
        ),
    ]
