# Generated by Django 5.2.6 on 2025-09-24 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('pub_infomation', models.TextField(blank=True, null=True, verbose_name='公開情報')),
                ('is_published', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
    ]
