# Generated by Django 4.0.3 on 2022-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_roomtype_number_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='room',
            name='mishuu_fee',
            field=models.IntegerField(default=0, verbose_name='滞納費'),
        ),
    ]
