# Generated by Django 5.2.6 on 2025-09-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_publicinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicinformation',
            old_name='pub_infomation',
            new_name='pub_information',
        ),
    ]
