# Generated by Django 5.2.7 on 2025-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0011_rename_pub_infomation_publicinformation_pub_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicinformation',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='タイトル'),
        ),
    ]
