# Generated by Django 4.0.3 on 2022-04-01 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0011_room_comment_room_mishuu_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=64, verbose_name='建物名'),
        ),
        migrations.AddField(
            model_name='room',
            name='house_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='room',
            name='municipality',
            field=models.CharField(blank=True, max_length=128, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='room',
            name='prefecture',
            field=models.CharField(blank=True, max_length=32, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='room',
            name='tel_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号はハイフン(-)無しです。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='room',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='郵便番号'),
        ),
    ]
