# Generated by Django 4.0.3 on 2022-04-01 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0012_room_building_room_house_number_room_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tel_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='電話番号はハイフン(-)無しです。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
