# Generated by Django 6.0.5 on 2026-06-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0012_publicinformation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='private_drainage_equipment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='専有部縦排水管'),
        ),
        migrations.AddField(
            model_name='overview',
            name='public_drainage_equipment',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='共用部縦排水管'),
        ),
    ]
