# 使用するベースイメージ。
FROM python:3-alpine
# stdoutへの出力をバッファリングさせない。(errorやlogを直ちに出力して欲しいから)
ENV PYTHONUNBUFFERED 1
# コンテナ環境にディレクトリを作成しておく。
RUN mkdir /code
# /code/ディレクトリを作業用ディレクトリにする。
WORKDIR /code
# requirements.txtファイルを/code/ディレクトリにコピーする。
COPY requirements.txt /code/
# https://github.com/python-pillow/docker-images/blob/master/alpine/Dockerfile
RUN apk add --update --no-cache g++ gcc \
            libc-dev \
            libstdc++ \
            make \
            openblas-dev \
            cairo cairo-dev pango pango-dev gdk-pixbuf \
            musl-dev jpeg-dev zlib-dev libffi-dev \
            font-noto-cjk

# 日本語対応(IPAフォントのインストール)
# https://ipafont.ipa.go.jp/old/ipafont/download.html
# https://gist.github.com/shichi-at-nttr/68550fb4c19c9737195a3f09cf5b1a9c
# RUN apk --no-cache add fontconfig \
#     && cd \
#     && wget https://ipafont.ipa.go.jp/IPAfont/ipagp00303.zip \
#     && unzip ipagp00303.zip \
#     && mkdir -p /usr/share/fonts/ipa \
#     && cp ipagp00303/ipagp.ttf /usr/share/fonts/ipa \
#     && fc-cache -fv

# alpineでTimeZoneをJSTにするための追加処理。
# https://qiita.com/tubutubu_mustard/items/17fc8bdebb3e9a3e8799
RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone
# pipコマンドを実行してrequirements.txtに記載してあるライブラリをインストールする。
RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.txt
# ホスト上のdjangoアプリ、データベースファイルなどを/code/ディレクトリにコピーする。
# docker-composeでマウントするが必要なのか？コメントアウトしても動作するが。
# https://docs.docker.com/compose/django/#define-the-project-components
COPY . /code/
