# Generated by Django 4.0.4 on 2022-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_user_flg', models.BooleanField(default=False, verbose_name='仮登録')),
            ],
        ),
    ]
