# Generated by Django 4.0.4 on 2022-05-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_controlrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlrecord",
            name="name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="コントロール名"
            ),
        ),
    ]
