# Generated by Django 5.0.6 on 2024-06-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='種別')),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='information.informationtype'),
        ),
    ]
