# Generated by Django 5.0.6 on 2024-06-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_informationtype_information_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='members_only',
            field=models.BooleanField(default=True),
        ),
    ]
